name: Test F
on:
  push:
    branches: [main]

jobs:
  test:
    uses: mochthebest-byte/ci-pipelines/.github/workflows/test-f.yml@main
    with:
      image_name: test
      ecr_repository: test
      service_name: test
      aws_region: us-east-1
      ci_role_arn: arn:aws:iam::428156589409:role/my-app-eks-github-ci
      gitops_repo: mochthebest-byte/gitops
    secrets:
      gitops_token: ${{ secrets.GITOPS_PAT }}
