name: Test Call Secrets
on:
  push:
    branches: [main]

jobs:
  test:
    uses: mochthebest-byte/ci-pipelines/.github/workflows/test-secrets.yml@main
    with:
      name: "World"
    secrets:
      my_secret: "test-value"
